#!/bin/bash
set -ex

# resize script phase 2

if ! [ -h /dev/disk/by-label/root ]; then
  echo "/dev/disk/by-label/root does not exist or is not a symlink. Don't know how to expand"
  return 0
fi

ROOT_PART=$(readlink /dev/disk/by-label/root)
/sbin/resize2fs $ROOT_PART
